/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/steam/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start Steam OpenID authentication */
        get: operations["authorizeWithSteam"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/steam/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify the Steam OpenID callback
         * @description Steam supplies its OpenID response fields in addition to the opaque state value.
         */
        get: operations["completeSteamAuthentication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange an authorization code or rotate a refresh token
         * @description Web refresh credentials are returned only as Secure, HttpOnly, SameSite cookies. Android refresh credentials
         *     are returned only in the response body. Cookie-based refresh requests require an allowlisted Origin and a
         *     matching X-CSRF-Token header/cookie value.
         */
        post: operations["exchangeAuthenticationToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current refresh-token family */
        post: operations["logoutCurrentSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke every refresh-token family for the authenticated subject */
        post: operations["logoutAllSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the authenticated user's synchronized Steam profile and library state */
        get: operations["getMySteamProfile"];
        put?: never;
        post?: never;
        /**
         * Permanently delete the authenticated user's account
         * @description Atomically removes the user's identity, profile, library, synchronization state, sessions, comparisons, cooldowns, personal ratings, and current global aggregate contributions. Non-user-specific game catalog data remains. Previously issued access and refresh credentials are invalid after completion.
         */
        delete: operations["deleteMyAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the authenticated user's imported Steam library */
        get: operations["getMySteamLibrary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/library-sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the authenticated user's latest synchronization job */
        get: operations["getMyLibrarySynchronization"];
        put?: never;
        /** Request or retrieve an active durable Steam library synchronization */
        post: operations["requestMyLibrarySynchronization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/library/{appId}/eligibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set the authenticated user's comparison-eligibility behavior for an owned game */
        put: operations["setMyGameEligibility"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the authenticated user's personal game leaderboard
         * @description Personal score is the conservative TrueSkill value mu minus three sigma and is not comparable to global score.
         */
        get: operations["getMyGameLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboards/global": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the public contributed-games global leaderboard
         * @description Global score is the capped precision-weighted mean and is not comparable to personal score.
         */
        get: operations["getGlobalGameLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comparisons/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Return the active comparison or allocate an MMR-selected pair */
        post: operations["getNextComparison"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comparisons/{comparisonId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Idempotently finalize the exact server-issued comparison
         * @description Game IDs, orientation, ratings, aggregation values, and model parameters are server-owned.
         */
        put: operations["submitComparisonResult"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TokenRequest: {
            /** @enum {string} */
            grant_type: "authorization_code" | "refresh_token";
            client_id: string;
            /** @description Single-use authorization code for the authorization_code grant. */
            code?: string;
            /** @description S256 PKCE verifier for the authorization_code grant. */
            code_verifier?: string;
            /** @description Android refresh credential; web clients use the protected cookie instead. */
            refresh_token?: string;
        };
        TokenResponse: {
            /** @description RS256 JWT valid for 15 minutes. */
            access_token: string;
            /** @constant */
            token_type: "Bearer";
            /** @constant */
            expires_in: 900;
            /** @description Present only for Android clients and valid for 30 days. */
            refresh_token?: string;
        };
        LibrarySyncJob: {
            /** Format: uuid */
            jobId: string;
            /** @enum {string} */
            trigger: "LOGIN" | "MANUAL";
            /** @enum {string} */
            status: "PENDING" | "RUNNING" | "RETRY_WAIT" | "SUCCEEDED" | "FAILED";
            attemptCount: number;
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            runAfter: string;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            completedAt?: string | null;
            /** @description Safe stable failure code; LIBRARY_UNAVAILABLE means Steam game details must be made public. */
            failureCode?: string | null;
        };
        MeProfile: {
            steamId64: string;
            displayName?: string | null;
            /** Format: uri */
            avatarUrl?: string | null;
            /** Format: uri */
            profileUrl?: string | null;
            /** @enum {string} */
            libraryState: "NOT_SYNCED" | "AVAILABLE" | "UNAVAILABLE";
            /** Format: date-time */
            lastProfileSyncAt?: string | null;
            /** Format: date-time */
            lastLibrarySyncAt?: string | null;
            synchronization?: components["schemas"]["LibrarySyncJob"] | null;
        };
        LibraryItem: {
            /** Format: int64 */
            appId: number;
            name: string;
            /** Format: uri */
            iconUrl?: string | null;
            /** Format: uri */
            artworkUrl: string;
            /** Format: int64 */
            playtimeMinutes: number;
            currentlyOwned: boolean;
            /** @enum {string} */
            eligibilityOverride: "DEFAULT" | "INCLUDED" | "EXCLUDED";
            effectivelyEligible: boolean;
            /** Format: date-time */
            firstImportedAt: string;
            /** Format: date-time */
            lastImportedAt: string;
        };
        LibraryPage: {
            items: components["schemas"]["LibraryItem"][];
            nextCursor?: string | null;
        };
        EligibilityRequest: {
            /** @enum {string} */
            behavior: "DEFAULT" | "INCLUDED" | "EXCLUDED";
        };
        ComparisonGame: {
            /** Format: int64 */
            appId: number;
            name: string;
            /** Format: uri */
            artworkUrl: string;
        };
        Comparison: {
            /** Format: uuid */
            comparisonId: string;
            left: components["schemas"]["ComparisonGame"];
            right: components["schemas"]["ComparisonGame"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
        };
        ComparisonResultRequest: {
            /** @enum {string} */
            outcome: "LEFT_WIN" | "RIGHT_WIN" | "DRAW" | "SKIP";
        };
        ComparisonResult: {
            /** Format: uuid */
            comparisonId: string;
            /** @enum {string} */
            outcome: "LEFT_WIN" | "RIGHT_WIN" | "DRAW" | "SKIP";
            /** Format: date-time */
            completedAt: string;
        };
        /** @enum {string} */
        RankingStatus: "PROVISIONAL" | "RANKED";
        PersonalLeaderboardEntry: {
            /**
             * Format: int64
             * @description One-based position in the complete filtered personal ordering.
             */
            rank: number;
            /** Format: int64 */
            appId: number;
            name: string;
            /** Format: uri */
            artworkUrl: string;
            /** @description Rounded transport value of personal mu minus three sigma; null without non-skip evidence and not comparable to global score. */
            score: number | null;
            /** @description Completed non-skip personal comparisons involving this game. */
            comparisonCount: number;
            status: components["schemas"]["RankingStatus"];
            currentlyOwned: boolean;
            effectivelyEligible: boolean;
        };
        PersonalLeaderboardPage: {
            items: components["schemas"]["PersonalLeaderboardEntry"][];
            nextCursor?: string | null;
        };
        GlobalLeaderboardEntry: {
            /**
             * Format: int64
             * @description One-based position in the complete global ordering.
             */
            rank: number;
            /** Format: int64 */
            appId: number;
            name: string;
            /** Format: uri */
            artworkUrl: string;
            /** @description Rounded transport value of weighted_mu_sum divided by precision_sum; not comparable to personal score. */
            score: number;
            contributorCount: number;
            status: components["schemas"]["RankingStatus"];
        };
        GlobalLeaderboardPage: {
            items: components["schemas"]["GlobalLeaderboardEntry"][];
            nextCursor?: string | null;
        };
        /** @description RFC 9457 Problem Details with request correlation. */
        Problem: {
            /**
             * Format: uri
             * @description Stable problem category identifier.
             */
            type: string;
            /** @description Short user-facing problem summary. */
            title: string;
            /** Format: int32 */
            status: number;
            /** @description Safe user-facing explanation without raw exception details. */
            detail: string;
            /** Format: uri-reference */
            instance?: string;
            /** @description Value returned in the X-Request-ID response header. */
            requestId: string;
        };
    };
    responses: {
        /** @description Safe RFC 9457 error response. */
        Problem: {
            headers: {
                /** @description Accepted or generated request correlation identifier. */
                "X-Request-ID"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        ClientId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authorizeWithSteam: {
        parameters: {
            query: {
                client_id: components["parameters"]["ClientId"];
                return_uri: string;
                code_challenge: string;
                code_challenge_method: "S256";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to Steam without issuing API credentials. */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    completeSteamAuthentication: {
        parameters: {
            query: {
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the registered client return URI with a single-use authorization code. */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    exchangeAuthenticationToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description A short-lived access token and client-appropriate refresh delivery. */
            200: {
                headers: {
                    /** @description Protected refresh and CSRF cookies for web clients only. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    logoutCurrentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session revoked; web authentication cookies are cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    logoutAllSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All sessions revoked; web authentication cookies are cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    getMySteamProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Minimal Steam profile and the latest synchronization summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeProfile"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    deleteMyAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account and all user-specific data were deleted; no representation is returned. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
        };
    };
    getMySteamLibrary: {
        parameters: {
            query?: {
                /** @description Opaque continuation cursor from the previous response. */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Imported current and historical ownership entries in stable App-ID order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
        };
    };
    getMyLibrarySynchronization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest durable synchronization job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibrarySyncJob"];
                };
            };
            /** @description No synchronization has been requested yet. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
        };
    };
    requestMyLibrarySynchronization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A new job was queued or the equivalent active job was returned. */
            202: {
                headers: {
                    Location?: "/api/v1/me/library-sync";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibrarySyncJob"];
                };
            };
            401: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    setMyGameEligibility: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EligibilityRequest"];
            };
        };
        responses: {
            /** @description Updated ownership entry with its effective eligibility. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryItem"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    getMyGameLeaderboard: {
        parameters: {
            query?: {
                /** @description Include imported games that are no longer owned. */
                includeHistorical?: boolean;
                /** @description Opaque, expiring continuation cursor from the previous response. */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current personal games, and historical games only when explicitly requested. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalLeaderboardPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
        };
    };
    getGlobalGameLeaderboard: {
        parameters: {
            query?: {
                /** @description Opaque, expiring continuation cursor from the previous response. */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Materialized games with at least one current aggregate contributor; no user-specific data is returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalLeaderboardPage"];
                };
            };
            400: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    getNextComparison: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The exact server-issued pair and its 24-hour submission window. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comparison"];
                };
            };
            401: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    submitComparisonResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comparisonId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparisonResultRequest"];
            };
        };
        responses: {
            /** @description The newly or previously recorded immutable outcome. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonResult"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
}
